### ISSUE TITLE
Creating an ERC20 token as part of my contract suite

### ISSUE THREAD

**Issue by pimhakkert** [solidstate-network/solidstate-solidity#167]
Hi, I saw in #156 that Premia is a decent example to use for using the SolidState library. I was looking for an example of an ERC20 token, and I have a few questions.

Premia uses a constructor in `contracts/PremiaErc20.sol` to define the name, symbol, etc... but I thought using a constructor is a big no-no with facets. What is up with that?

Also, and this question is probably more aimed towards the diamond pattern than this library, once I deploy an ERC20 facet, how do I interact with it as I'd do with a regular ERC20? Usually when you deploy a contract you interact with it using its address, but this is a diamond facet, so instead I interact with the Diamond. How can I make sure I am referring to the ERC20 token, especially if I might end up using multiple of them in my implementation?

This raises a potential next issue: How can third parties interact with my ERC20 token? So far I've only worked with OpenZeppelin's ERC contracts and so far they show up perfectly on DEX'es. I'm curious if there are any differences here.

My apologies for being clueless about this. It's quite new for me 😃 
Thank you for any help you can offer.

**Comment by ItsNickBarry** [comment]
> but I thought using a constructor is a big no-no with facets

Implementation contracts (such as facets) cannot use constructors that modify storage, because the storage will be set on the implementation rather than on the proxy.  This does not apply to `immutable` variables, which are stored in the bytecode and therefore accessible by the proxy.  All of the Premia `Pool` facets do this.  I don't recall exactly how `PremiaErc20` fits into this, but the same rules apply.

> How can I make sure I am referring to the ERC20 token, especially if I might end up using multiple of them in my implementation?

I suggest creating a meta-interface that includes the interfaces of all of the facets (see Premia `IPool.sol`).  Then use that interface and the proxy address when interacting.

It is not possible to define multiple ERC20s on a single proxy.  See ERC1155.

> How can third parties interact with my ERC20 token?

Any contract that follows the [standard](https://eips.ethereum.org/EIPS/eip-20) can be interacted with in the same way.  Third parties can call the same set of functions using the standard interface, and they can read the emitted events.

---

If you have more questions like this, ask them in the SolidState discord.
