### ISSUE TITLE
Operator Filter

### ISSUE THREAD

**Issue by zdenham** [solidstate-network/solidstate-solidity#218]
Wanted to gauge if there is any appetite to support the https://github.com/ProjectOpenSea/operator-filter-registry 

This is a set of utility modifiers which allows collections to selectively ban marketplaces which don't pay out creator royalties by subscribing to a "registry".

As a whole, I'm not a huge fan of the filter registries, but NFT collections consistently are implementing the operator filter.

Currently with SS the best way to implement operator registry AFAIK is to clone and own ERC721Base.sol and include the modifiers there. 

This might be made simpler if `ERC721Base` functions were marked as `virtual`

**Comment by ItsNickBarry** [comment]
I worked briefly with the filter registry in the past, and if I recall correctly it worked as-is with SS because it doesn't use storage.  I would consider this to be a third-party integration rather than a universal standard, so I don't think it's going to be included in the main SS repository.

I'll try to address your concerns about modifiers and overrides alongside #210.  If you have anything else to add, please post on that issue.

**Comment by zdenham** [comment]
Thanks for the response, will move discussion over to #210
