### ISSUE TITLE
Add Upgradeable Proxy

### ISSUE THREAD

**Issue by ItsNickBarry** [solidstate-network/solidstate-solidity#62]
I've neglected this feature because I don't understand the attack vector that lead to the creation of the "transparent proxy" pattern.  This needs a bit of research.

Premia has an implementation that can probably be copied mostly intact: https://github.com/Premian-Labs/premia-contracts/blob/master/contracts/ProxyUpgradeableOwnable.sol

Tests should be added.

**Comment by NouDaimon** [comment]
Thank you for the assignment Nick.

From some preliminary research, I have understood the following:

1. Function clashing between the proxy and the proxy's implementation open an attack vector. These vectors change in nature in every case, depending on the proxy and its implementation code. 
Ref: https://medium.com/nomic-labs-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357

2. An example of an attack from function clashing may occur in a proxy with ERC20 implementation by clashing a function which burns tokens with a function which transfers them.
Ref: https://forum.openzeppelin.com/t/beware-of-the-proxy-learn-how-to-exploit-function-clashing/1070

A `Transparent Proxy`  eradicates this vector by forwarding calls based on `msg.sender`. Regardless of selector matching, if `msg.sender`  is not the owner of the proxy, then the function will be forwarded via `delegateCall`. 

I hope this serves as a succinct introduction into the attack vector space of proxies.

I want to also add, I have not thought or explored how this may affect Diamonds.

**Comment by ItsNickBarry** [comment]
What I don't understand is how the existence of the transparent proxy helps the situation.  If the contract owner is malicious, he or she will simply deploy a regular proxy instead of a transparent proxy.  The regular proxy could even be named `TransparentProxy` to trick users into thinking that it's safe.  In most cases where the contract owner is a malicious actor, the scam is complete before the world has time to audit the contract code in detail.

So, for now I think we should add a standard proxy, and perhaps the next step will be to add a transparent proxy.  Another argument for transparent proxies (implied in the first article) is that avoiding accidental selector clashes might be a better development experience.

**Comment by NouDaimon** [comment]
Hmmm. My best guess is that `TransparentProxy` prevents the owner from adding malicious code later on, via upgrading the proxy itself, which is harder to pick up on as opposed to the initial deployment of the proxy itself, where malicious code is far easier to spot, generally (and credible deployments request audits so it can be caught there most likely).

In that sense it could just be a new standard to be applied to increase trustworthiness in a project, even though it does not really prevent the attack vector per se, as the injector is the owner of the proxy themselves. 

I concur; the benefit is marginal and the gas overhead caused by the additional check perhaps does not outweigh neither the dev experience gain nor the credibility gained by virtue of "transparency".
